export const MODELS = [
  { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro', desc: '推理最强，适合复杂任务' },
  { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash', desc: '性能均衡，通用性强' },
  { id: 'gemini-3.1-flash-lite-preview', name: 'Gemini 3.1 Flash Lite', desc: '速度最快，响应迅速' },
];

export const TRANSLATIONS = {
  zh: {
    title: '学习助手',
    subtitle: '智能识别题目，一键提取解析，或生成专属语音讲解。支持函数绘图。',
    extractorMode: '题目提取',
    audioTutorMode: '语音讲题',
    readingCorrectionMode: '朗读纠错',
    grapherMode: '函数绘图仪',
    uploading: '上传文件中...',
    generating: '生成讲题音频中...',
    audioTutorPrompt: '这是一道题目的图片。请直接给出详细的讲解。不要念题目。如果是选择题，请详细解释每个选项为什么对、为什么错；如果是判断题，请指出错在哪里。语言要自然、口语化，适合作为语音讲解的文案。',
    liveQnA: '实时语音答疑',
    textContent: '讲解文字内容',
    endLive: '结束通话',
    startLive: '开始通话',
    listening: '正在聆听...',
    speaking: 'AI 正在讲话...',
    upload: '上传图片',
    camera: '拍照识别',
    add: '添加',
    clear: '清空',
    start: '开始提取',
    parsing: '解析中...',
    selected: '已选',
    preview: '识别预览',
    ready: '题已就绪',
    back: '返回列表',
    questionContent: '题干内容',
    copy: '复制题干',
    copied: '已复制',
    answer: '答案',
    explanation: '讲解与分析',
    precautions: '注意事项',
    aiChat: 'AI 智能答疑',
    askMe: '对这道题还有疑问？试试快速提问：',
    placeholder: '输入你的问题，按 Enter 发送...',
    thinking: 'AI 思考中...',
    summaryAction: '总结考点',
    exampleAction: '举个例子',
    pitfallAction: '易错点提醒',
    retry: '重试',
    associateTextbook: '关联教材',
    manageTextbooks: '管理教材',
    selectTextbook: '选择教材...',
    fetchingTextbook: '正在获取教材内容...',
    zhangJingyangTitle: '张景洋模式',
    zhangJingyangSubtitle: '“你能别尬黑吗”',
    zhangJingyangEmpty: '感觉最近心情过于舒畅？来和张酱对话吧',
    zhangJingyangSwitchAvatar: '切换头像',
    zhangJingyangPlaceholder: '输入你想说的话...',
    zhangJingyangMathName: '霸王龙',
    zhangJingyangMathDesc: '',
    zhangJingyangEnglishName: '三角龙',
    zhangJingyangEnglishDesc: '',
    zhangJingyangChineseName: '迅猛龙',
    zhangJingyangChineseDesc: '',
    zhangJingyangInstructions: '使用指引',
    zhangJingyangInstruction1: '点击左侧电话图标开启实时语音对线。',
    zhangJingyangInstruction2: '切换不同学科模型以获得不同的对线体验。',
    zhangJingyangInstruction3: '张酱说话比较“委婉”，请做好心理准备。',
    organicModeTitle: '有机大题通关',
    organicModeSubtitle: '“你的专属有机推断与机理可视化实验室”',
    organicModeEmpty: '上传有机推断大题图片，或直接输入反应条件，我将为你推导路线并绘制机理图。',
    organicModePlaceholder: '输入有机反应、物质或上传大题图片...',
    organicModeInstructions: '使用指引',
    organicModeInstruction1: '点击左侧图片图标上传有机大题的流程图或题目截图。',
    organicModeInstruction2: '我可以为你推导 A→B→C 的合成路线，并解释每一步的反应条件。',
    organicModeInstruction3: '遇到不懂的反应机理（如消去、加成、取代），我会为你绘制带电子转移箭头的 SVG 动态图解。',
    organicModeInstruction4: '支持同分异构体穷举指导，帮你理清不饱和度与骨架结构。',
    organicModeQuickAction1: '解析 A→B',
    organicModeQuickAction2: '分析同分异构体',
    organicModeQuickAction3: '总结反应条件',
    organicModeCopySvg: '复制 SVG',
  },
  en: {
    title: 'Study Assistant',
    subtitle: 'Smartly extract questions, generate personalized audio explanations, or plot functions.',
    extractorMode: 'Question Extractor',
    audioTutorMode: 'Audio Tutor',
    readingCorrectionMode: 'Reading Correction',
    grapherMode: 'Graphing Calculator',
    uploading: 'Uploading file...',
    generating: 'Generating audio...',
    audioTutorPrompt: 'This is an image of a question. Please provide a detailed explanation directly. Do NOT read the question text. For multiple-choice questions, explain why each option is correct or incorrect; for true/false questions, point out where the error is. Use a natural, conversational tone suitable for an audio explanation script.',
    liveQnA: 'Live Voice Q&A',
    textContent: 'Explanation Text',
    endLive: 'End Call',
    startLive: 'Start Call',
    listening: 'Listening...',
    speaking: 'AI is speaking...',
    upload: 'Upload Image',
    camera: 'Camera Scan',
    add: 'Add',
    clear: 'Clear',
    start: 'Extract Now',
    parsing: 'Parsing...',
    selected: 'Selected',
    preview: 'Preview Results',
    ready: 'questions ready',
    back: 'Back to List',
    questionContent: 'Question Text',
    copy: 'Copy Text',
    copied: 'Copied',
    answer: 'Answer',
    explanation: 'Explanation & Analysis',
    precautions: 'Important Notes',
    aiChat: 'AI Tutor',
    askMe: 'Have questions? Try quick actions:',
    placeholder: 'Type your question, press Enter...',
    thinking: 'AI is thinking...',
    summaryAction: 'Summarize Key Points',
    exampleAction: 'Give an Example',
    pitfallAction: 'Common Pitfalls',
    retry: 'Retry',
    associateTextbook: 'Associate Textbook',
    manageTextbooks: 'Manage Textbooks',
    selectTextbook: 'Select textbook...',
    fetchingTextbook: 'Fetching textbook content...',
    zhangJingyangTitle: 'Zhang Jingyang Mode',
    zhangJingyangSubtitle: '"Can you stop being a hater?"',
    zhangJingyangEmpty: 'Feeling too happy lately? Come talk to Zhang-chan.',
    zhangJingyangSwitchAvatar: 'Switch Avatar',
    zhangJingyangPlaceholder: 'Type something...',
    zhangJingyangMathName: 'Tyrannosaurus',
    zhangJingyangMathDesc: '',
    zhangJingyangEnglishName: 'Triceratops',
    zhangJingyangEnglishDesc: '',
    zhangJingyangChineseName: 'Velociraptor',
    zhangJingyangChineseDesc: '',
    zhangJingyangInstructions: 'Usage Guide',
    zhangJingyangInstruction1: 'Click the phone icon to start live voice debate.',
    zhangJingyangInstruction2: 'Switch between subject models for different experiences.',
    zhangJingyangInstruction3: 'Zhang-chan is "subtle", please be mentally prepared.',
    organicModeTitle: 'Organic Master',
    organicModeSubtitle: '"Your personal organic synthesis & mechanism lab"',
    organicModeEmpty: 'Upload an organic chemistry problem image, or type a reaction. I will deduce the route and draw the mechanism.',
    organicModePlaceholder: 'Type a reaction, substance, or upload a problem image...',
    organicModeInstructions: 'Usage Guide',
    organicModeInstruction1: 'Click the image icon to upload a flowchart or screenshot of an organic chemistry problem.',
    organicModeInstruction2: 'I can deduce the A→B→C synthesis route and explain the reaction conditions for each step.',
    organicModeInstruction3: 'For complex mechanisms (e.g., elimination, addition), I will draw SVG diagrams with electron transfer arrows.',
    organicModeInstruction4: 'Supports step-by-step guidance for finding isomers, helping you clarify degrees of unsaturation and skeletons.',
    organicModeQuickAction1: 'Analyze A→B',
    organicModeQuickAction2: 'Analyze Isomers',
    organicModeQuickAction3: 'Summarize Conditions',
    organicModeCopySvg: 'Copy SVG',
  }
};
