export const MODELS = [
  { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro', desc: '最强推理，适合复杂题目' },
  { id: 'gemini-3-pro-preview', name: 'Gemini 3 Pro', desc: '性能均衡，通用性强' },
  { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash', desc: '速度最快，响应迅速' },
];

export const TRANSLATIONS = {
  zh: {
    title: '学习助手',
    subtitle: '智能识别题目，一键提取解析，或生成专属语音讲解。支持函数绘图。',
    extractorMode: '题目提取',
    audioTutorMode: '语音讲题',
    readingCorrectionMode: '朗读纠错',
    grapherMode: '函数绘图仪',
    uploading: '上传文件中...',
    generating: '生成讲题音频中...',
    audioTutorPrompt: '这是一道题目的图片。请直接给出详细的讲解。不要念题目。如果是选择题，请详细解释每个选项为什么对、为什么错；如果是判断题，请指出错在哪里。语言要自然、口语化，适合作为语音讲解的文案。',
    liveQnA: '实时语音答疑',
    textContent: '讲解文字内容',
    endLive: '结束通话',
    startLive: '开始通话',
    listening: '正在聆听...',
    speaking: 'AI 正在讲话...',
    upload: '上传图片',
    camera: '拍照识别',
    add: '添加',
    clear: '清空',
    start: '开始提取',
    parsing: '解析中...',
    selected: '已选',
    preview: '识别预览',
    ready: '题已就绪',
    back: '返回列表',
    questionContent: '题干内容',
    copy: '复制题干',
    copied: '已复制',
    answer: '答案',
    explanation: '讲解与分析',
    precautions: '注意事项',
    aiChat: 'AI 智能答疑',
    askMe: '对这道题还有疑问？试试快速提问：',
    placeholder: '输入你的问题，按 Enter 发送...',
    thinking: 'AI 思考中...',
    summaryAction: '总结考点',
    exampleAction: '举个例子',
    pitfallAction: '易错点提醒',
    retry: '重试',
    associateTextbook: '关联教材',
    manageTextbooks: '管理教材',
    selectTextbook: '选择教材...',
    fetchingTextbook: '正在获取教材内容...',
  },
  en: {
    title: 'Study Assistant',
    subtitle: 'Smartly extract questions, generate personalized audio explanations, or plot functions.',
    extractorMode: 'Question Extractor',
    audioTutorMode: 'Audio Tutor',
    readingCorrectionMode: 'Reading Correction',
    grapherMode: 'Graphing Calculator',
    uploading: 'Uploading file...',
    generating: 'Generating audio...',
    audioTutorPrompt: 'This is an image of a question. Please provide a detailed explanation directly. Do NOT read the question text. For multiple-choice questions, explain why each option is correct or incorrect; for true/false questions, point out where the error is. Use a natural, conversational tone suitable for an audio explanation script.',
    liveQnA: 'Live Voice Q&A',
    textContent: 'Explanation Text',
    endLive: 'End Call',
    startLive: 'Start Call',
    listening: 'Listening...',
    speaking: 'AI is speaking...',
    upload: 'Upload Image',
    camera: 'Camera Scan',
    add: 'Add',
    clear: 'Clear',
    start: 'Extract Now',
    parsing: 'Parsing...',
    selected: 'Selected',
    preview: 'Preview Results',
    ready: 'questions ready',
    back: 'Back to List',
    questionContent: 'Question Text',
    copy: 'Copy Text',
    copied: 'Copied',
    answer: 'Answer',
    explanation: 'Explanation & Analysis',
    precautions: 'Important Notes',
    aiChat: 'AI Tutor',
    askMe: 'Have questions? Try quick actions:',
    placeholder: 'Type your question, press Enter...',
    thinking: 'AI is thinking...',
    summaryAction: 'Summarize Key Points',
    exampleAction: 'Give an Example',
    pitfallAction: 'Common Pitfalls',
    retry: 'Retry',
    associateTextbook: 'Associate Textbook',
    manageTextbooks: 'Manage Textbooks',
    selectTextbook: 'Select textbook...',
    fetchingTextbook: 'Fetching textbook content...',
  }
};
